# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95753d8ab5cc5eeca0ec0cc32222e1b42821b051a4042b2d0bd288fed83def9ee76c9c484502f5d38505935238fd24b2e6a8f510363a4adcf3c3898f9a19d22e

test:
  secret_key_base: e7ca8791806870b996f818c403a2c1c7b4f5394be2c35ec14330bf4885286176ca4846b1a2439b20e924ef71466a0ff1e32772467e1717c515137bdf66763785

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
